version: "0.2"
ignorePaths:
  - .git
  - "**/.gitignore"
  - bun.lock
  - bun.lockb
  - "**/generated"
  - "**/prisma/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - anthropics
  - dbname
  - dotenv
  - ntvs
  - oneline
  - pkey
  - wada
  - wireframes
  - apigatewayv
  - auggie
  - Auggie
  - AUGGIE
  - automations
  - Avant
  - Avenir
  - awsdns
  - bierner
  - biomejs
  - Bluch
  - bunx
  - chax-at
  - CICD
  - clippy
  - DBNAME
  - Dockerfiles
  - dotenvx
  - dport
  - elif
  - émojis
  - Entra
  - Español
  - esac
  - evenodd
  - fabbrica
  - fdisk
  - gdisk
  - Groot
  - hono
  - hostnames
  - ichiro
  - Ichiro
  - initialised
  - ipsets
  - jiro
  - Jiro
  - kato
  - Kato
  - kenta
  - Kenta
  - Mcpjson
  - Msal
  - msie
  - mydb
  - ncat
  - netcat
  - neverthrow
  - nftables
  - npmjs
  - pino
  - pipefail
  - PKCE
  - pkill
  - POSTROUTING
  - pycache
  - quramy
  - qwen
  - Qwen
  - QWEN
  - sato
  - Sato
  - schemaname
  - serverlessv
  - socketsecurity
  - sqli
  - statsig
  - tablename
  - tanaka
  - Tanaka
  - tfstate
  - tfvars
  - trixie
  - tsgo
  - TXXX
  - uvx
  - venv
  - VITE
  - vitest
  - worktree
  - worktrees
  - yosuke
  - Yosuke
ignoreWords: []
import: []
