version: "0.2"
ignorePaths:
  - .git
  - "**/.gitignore"
  - bun.lock
  - bun.lockb
  - "**/generated"
  - "**/prisma/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - addgroup
  - Cladex
  - adduser
  - albls
  - anthropics
  - apigatewayv
  - auggie
  - Auggie
  - AUGGIE
  - automations
  - Avant
  - Avenir
  - awsdns
  - awslocal
  - bierner
  - biomejs
  - Bluch
  - bunx
  - cflist
  - chax-at
  - CICD
  - clippy
  - dbname
  - DBNAME
  - dbseed
  - dnsutils
  - Dockerfiles
  - dotenv
  - dotenvx
  - dport
  - ecrimg
  - ecrls
  - ecsls
  - ecsstop
  - ecssvc
  - ecstask
  - elbv
  - elif
  - émojis
  - Entra
  - esac
  - Español
  - evenodd
  - fabbrica
  - Fabbrica
  - fdisk
  - fgrep
  - fieldsets
  - gdisk
  - ghal
  - ghas
  - ghis
  - ghisl
  - ghisv
  - ghpr
  - ghprc
  - ghprl
  - ghprm
  - ghprs
  - ghprv
  - ghrv
  - ghrw
  - grba
  - grbc
  - Groot
  - gstp
  - hono
  - hostnames
  - hotspots
  - HSTS
  - ichiro
  - Ichiro
  - initialised
  - ipsets
  - jiro
  - Jiro
  - kato
  - Kato
  - kenta
  - Kenta
  - localstack
  - Mcpjson
  - Msal
  - msdownload
  - msie
  - myapp
  - mydb
  - NACLs
  - ncat
  - netcat
  - neverthrow
  - nftables
  - npmjs
  - ntvs
  - nums
  - nuxt
  - oklch
  - oneline
  - pino
  - pipefail
  - PKCE
  - pkey
  - pkill
  - popstate
  - POSTROUTING
  - presign
  - proddb
  - psql
  - pycache
  - quramy
  - qwen
  - Qwen
  - QWEN
  - rdsls
  - rdsstart
  - Refetches
  - rgba
  - sato
  - Sato
  - schemaname
  - secget
  - secls
  - serverlessv
  - sgls
  - socketsecurity
  - sqli
  - statsig
  - subnetls
  - tablename
  - tanaka
  - Tanaka
  - tappable
  - tfsl
  - tfss
  - tfstate
  - tfvars
  - tfwl
  - tfws
  - trixie
  - tsgo
  - TXXX
  - uvx
  - venv
  - VITE
  - vitest
  - vpcls
  - wada
  - WCAG
  - wireframes
  - worktree
  - worktrees
  - yosuke
  - Yosuke
ignoreWords: []
import: []
